### ISSUE TITLE
Having problems with arrays

### ISSUE THREAD

**Issue by ghost** [zardoy/modify-json-file#6]
Hey, So I've been trying to use this package for a queue system im working on and I've been having problems with arrays. I've been trying to use **modifyJsonFile** to do this but when I try to change the array, it doesnt update properly, Here's what I mean.
Code:
```ts
//imports and other stuff
async function addtoqueue(userid: string): Promise<void> {
    const inqueue = queue.users
    const newqueue = inqueue.push(userid)
    const status = queue.status
    const playercount = queue.queueCount + 1
    await modifyJsonFile(
     "./src/jsons/queue.json", {
          status: status,
          users: newqueue,
          queueCount: playercount
      })
}
```
The JSON file thats produced:
```json
{
    "status": "open",
    "users": 2,
    "queueCount": 1
}
```
How can I fix this?

**Comment by zardoy** [comment]
Heeey! Thank you so much for trying this library!

With the code you provided I think the problem is that `inqueue.push(userid)` returns the length of new array, not the array itself. Try to replace `users: newqueue` with `users: inqueue`, we fully support arrays :)

Like so:

```ts
//imports and other stuff
async function addtoqueue(userid: string): Promise<void> {
    const inqueue = queue.users
    const newqueue = inqueue.push(userid)
    const status = queue.status
    const playercount = queue.queueCount + 1
    await modifyJsonFile(
     "./src/jsons/queue.json", {
          status: status,
          users: inqueue,
          queueCount: playercount
      })
}
```

Also note that if property is missing in original file you need to pass `{ifPropertyIsMissing: 'add'}` as third argument

Feel free to ask questions!

**Comment by ghost** [comment]
It works, thank you so much.
